-- =============================================================================
-- Achievements: per-game catalogs + per-user unlock records.
-- =============================================================================
--
-- Design summary (full write-up: docs/ACHIEVEMENTS.md):
--   * public.games / public.achievements  – canonical catalog metadata, read-only to clients.
--   * public.user_achievements            – one tiny row per unlock (user, achievement, time).
--   * public.sync_achievements(...)       – the ONLY client write path. Idempotent, batched.
--   * public.get_my_achievements(...)     – reconciliation read for one game.
--
-- Security model:
--   * Clients authenticate with a normal Supabase Auth JWT (see the `supabase-session` action
--     of the patreon-middleware Edge Function). The user id is ALWAYS auth.uid(); no function
--     accepts a user id argument.
--   * Clients have NO insert/update/delete grants on any table. Writes go through
--     private.sync_achievements (SECURITY DEFINER, search_path = '', not in an exposed schema),
--     reached via a SECURITY INVOKER wrapper in public.
--   * Supabase's default privileges grant ALL on new public tables/functions to anon and
--     authenticated. RLS policies do not remove grants, so every grant below is explicit.
--
-- Catalog invariants (enforced by triggers, not just documented):
--   * (game_id, achievement_key, bit_index) of an achievement never change after insert.
--   * Achievements are never hard-deleted (a deleted row would free its bit_index for reuse and
--     silently remap old clients' local bitsets). Retire them with is_retired = true instead.
--   * Any catalog change bumps games.catalog_version, so exported manifests are versioned.
-- =============================================================================

create schema if not exists private;
revoke all on schema private from public;
-- authenticated needs USAGE so the public wrapper can call into private. The schema is not in
-- the API's exposed schemas, so nothing in it is reachable over PostgREST directly.
grant usage on schema private to authenticated;

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

create table public.games (
  id              bigint generated by default as identity primary key,
  slug            text        not null unique
                    check (slug ~ '^[a-z0-9]([a-z0-9-]{0,62}[a-z0-9])?$'),
  name            text        not null check (char_length(name) between 1 and 200),
  is_active       boolean     not null default true,
  catalog_version integer     not null default 1 check (catalog_version >= 1),
  created_at      timestamptz not null default now()
);

comment on table public.games is
  'Games that own an achievement catalog. is_active = false hides an unreleased game''s catalog from clients.';

create table public.achievements (
  id                 bigint generated by default as identity primary key,
  game_id            bigint      not null references public.games (id) on delete cascade,
  achievement_key    text        not null
                       check (achievement_key ~ '^[a-zA-Z0-9]([a-zA-Z0-9_.-]{0,62}[a-zA-Z0-9])?,
  title              text        not null check (char_length(title) between 1 and 200),
  description        text        not null check (char_length(description) <= 1000),
  localization_table text        null check (localization_table is null or char_length(localization_table) between 1 and 200),
  title_key          text        null check (title_key is null or char_length(title_key) between 1 and 200),
  description_key    text        null check (description_key is null or char_length(description_key) between 1 and 200),
  icon_path          text        null check (icon_path is null or char_length(icon_path) between 1 and 500),
  -- When non-null the client downloads icon_url first; on any failure it falls back to icon_path.
  -- Priority: icon_url (ok) -> icon_path -> fallback.png -> DefaultIcon (code-generated)
  icon_url           text        null
                       check (icon_url is null or char_length(icon_url) between 1 and 2000),
  hidden             boolean     not null default false,
  is_retired         boolean     not null default false,
  display_order      smallint    not null default 0,
  -- Position in the client's local unlock bitset. Immutable, never reused. 4096 bits = 512 bytes.
  bit_index          integer     not null check (bit_index between 0 and 4095),
  created_at         timestamptz not null default now(),

  constraint achievements_game_key_unique unique (game_id, achievement_key),
  constraint achievements_game_bit_unique unique (game_id, bit_index),
  constraint achievements_localization_keys_need_table
    check ((title_key is null and description_key is null) or localization_table is not null)
);

comment on column public.achievements.bit_index is
  'Immutable local bitset position. Append new achievements with new indexes; never reorder or reuse.';
comment on column public.achievements.is_retired is
  'Retired achievements stay forever (their bit_index is burned) but sync_achievements rejects them.';
comment on column public.achievements.icon_url is
  'Optional remote URL for the achievement icon. Client downloads this first; on any failure falls '
  'back to icon_path. Leave NULL to use icon_path only. '
  'Priority: icon_url (ok) -> icon_path -> fallback.png -> DefaultIcon (code-generated).';

-- Exactly 1 row per user per game storing unlocked achievement IDs as a BIGINT array.
create table public.user_achievements (
  user_id         uuid        not null references auth.users (id) on delete cascade,
  game_id         bigint      not null references public.games (id) on delete cascade,
  achievement_ids bigint[]    not null default '{}',
  updated_at      timestamptz not null default now(),
  primary key (user_id, game_id)
);

comment on table public.user_achievements is
  'Exactly 1 row per user per game storing unlocked achievement IDs as a BIGINT array.';

create index if not exists idx_user_achievements_ids on public.user_achievements using gin (achievement_ids);

-- -----------------------------------------------------------------------------
-- Catalog invariants
-- -----------------------------------------------------------------------------

create function private.guard_achievement_identity()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    if new.id <> old.id
       or new.game_id <> old.game_id
       or new.achievement_key <> old.achievement_key
       or new.bit_index <> old.bit_index then
      raise exception 'achievement id, game_id, achievement_key and bit_index are immutable (achievement %)', old.id
        using errcode = 'P0001';
    end if;
    return new;
  end if;

  -- DELETE: blocked unless an operator explicitly opts in for this transaction, e.g. to purge a
  -- game that never shipped:  set local achievements.allow_hard_delete = 'on';
  if coalesce(current_setting('achievements.allow_hard_delete', true), '') <> 'on' then
    raise exception 'achievements must be retired (is_retired = true), not deleted: bit_index % of game % may never be reused', old.bit_index, old.game_id
      using errcode = 'P0001';
  end if;
  return old;
end;
$$;

create trigger achievements_guard_identity
  before update or delete on public.achievements
  for each row execute function private.guard_achievement_identity();

create function private.bump_catalog_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.games
     set catalog_version = catalog_version + 1
   where id = coalesce(new.game_id, old.game_id);
  return null;
end;
$$;

create trigger achievements_bump_catalog_version_on_write
  after insert or delete on public.achievements
  for each row execute function private.bump_catalog_version();

create trigger achievements_bump_catalog_version_on_update
  after update on public.achievements
  for each row
  when (old is distinct from new)
  execute function private.bump_catalog_version();

revoke all on function private.guard_achievement_identity() from public;
revoke all on function private.bump_catalog_version() from public;

-- -----------------------------------------------------------------------------
-- Grants (explicit; RLS alone does not revoke Supabase's default table grants)
-- -----------------------------------------------------------------------------

revoke all on table public.games, public.achievements, public.user_achievements from anon, authenticated;

grant select on table public.games, public.achievements to anon, authenticated;
grant select on table public.user_achievements to authenticated;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

alter table public.games enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;

create policy "Active game catalogs are readable"
  on public.games
  for select
  to anon, authenticated
  using (is_active);

create policy "Achievements of active games are readable"
  on public.achievements
  for select
  to anon, authenticated
  using (exists (select 1 from public.games g where g.id = achievements.game_id and g.is_active));

create policy "Users can read their own unlocks"
  on public.user_achievements
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- No insert/update/delete policies exist for any client role: those operations are also denied
-- at the grant level above, so a future accidental grant still hits RLS.

-- -----------------------------------------------------------------------------
-- Sync (the only client write path)
-- -----------------------------------------------------------------------------

create or replace function private.sync_achievements(p_game_id bigint, p_achievement_ids bigint[])
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id     uuid := auth.uid();
  v_valid_ids   bigint[];
  v_rejected    bigint[];
  v_existing    bigint[];
  v_new_ids     bigint[];
  v_merged      bigint[];
  v_inserted    integer := 0;
begin
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if coalesce(cardinality(p_achievement_ids), 0) > 256 then
    raise exception 'batch_too_large' using errcode = 'P0001', hint = 'Send at most 256 achievement ids per call.';
  end if;

  if p_game_id is null or not exists (select 1 from public.games g where g.id = p_game_id) then
    raise exception 'unknown_game' using errcode = 'P0001';
  end if;

  -- Filter IDs that actually exist in this game and are not retired
  select coalesce(array_agg(a.id order by a.id), '{}')
    into v_valid_ids
    from public.achievements a
   where a.game_id = p_game_id
     and not a.is_retired
     and a.id = any(p_achievement_ids);

  -- Rejected IDs (unknown to game or retired)
  select coalesce(array_agg(distinct req.id order by req.id), '{}')
    into v_rejected
    from unnest(p_achievement_ids) as req(id)
   where req.id is not null
     and not (req.id = any(v_valid_ids));

  -- Get currently unlocked array for this user & game
  select coalesce(ua.achievement_ids, '{}')
    into v_existing
    from public.user_achievements ua
   where ua.user_id = v_user_id
     and ua.game_id = p_game_id;

  if v_existing is null then
    v_existing := '{}';
  end if;

  -- Find newly unlocked IDs not yet in existing array
  select coalesce(array_agg(v.id order by v.id), '{}')
    into v_new_ids
    from unnest(v_valid_ids) as v(id)
   where not (v.id = any(v_existing));

  v_inserted := coalesce(cardinality(v_new_ids), 0);

  -- Merge existing + new (distinct and sorted)
  select coalesce(array_agg(distinct u.id order by u.id), '{}')
    into v_merged
    from unnest(v_existing || v_new_ids) as u(id);

  -- Upsert the single row
  insert into public.user_achievements (user_id, game_id, achievement_ids, updated_at)
  values (v_user_id, p_game_id, v_merged, now())
  on conflict (user_id, game_id) do update set
    achievement_ids = excluded.achievement_ids,
    updated_at = now();

  return jsonb_build_object(
    'accepted', to_jsonb(v_valid_ids),
    'rejected', to_jsonb(v_rejected),
    'inserted', v_inserted
  );
end;
$$;

revoke all on function private.sync_achievements(bigint, bigint[]) from public;
grant execute on function private.sync_achievements(bigint, bigint[]) to authenticated;

create or replace function public.sync_achievements(p_game_id bigint, p_achievement_ids bigint[])
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.sync_achievements(p_game_id, p_achievement_ids);
$$;

comment on function public.sync_achievements(bigint, bigint[]) is
  'Idempotent batched unlock upload for auth.uid(). Returns {accepted[], rejected[], inserted}.';

revoke all on function public.sync_achievements(bigint, bigint[]) from public, anon;
grant execute on function public.sync_achievements(bigint, bigint[]) to authenticated;

-- -----------------------------------------------------------------------------
-- Reconciliation read
-- -----------------------------------------------------------------------------

create or replace function public.get_my_achievements(p_game_id bigint)
returns table (achievement_id bigint, unlocked_at timestamptz)
language sql
stable
security invoker
set search_path = ''
as $$
  select unnest(ua.achievement_ids) as achievement_id,
         ua.updated_at as unlocked_at
    from public.user_achievements ua
   where ua.user_id = (select auth.uid())
     and ua.game_id = p_game_id
   order by achievement_id;
$$;

comment on function public.get_my_achievements(bigint) is
  'Unlocked achievement ids for auth.uid() in one game. RLS-scoped (security invoker).';

revoke all on function public.get_my_achievements(bigint) from public, anon;
grant execute on function public.get_my_achievements(bigint) to authenticated;

-- -----------------------------------------------------------------------------
-- Readable View
-- -----------------------------------------------------------------------------

create or replace view public.user_achievements_readable as
select 
    ua.user_id,
    ua.game_id,
    a.id as achievement_id,
    a.achievement_key,
    a.title as achievement_title,
    ua.updated_at as unlocked_at
from public.user_achievements ua
cross join lateral unnest(ua.achievement_ids) as u(ach_id)
join public.achievements a on a.id = u.ach_id;

grant select on public.user_achievements_readable to authenticated;
